# ARG BASE_IMAGE=nvcr.io/nvidia/jetson-voice:r32.4.2
ARG BASE_IMAGE=nvcr.io/nvidia/l4t-ml:r32.6.1-py3

FROM ${BASE_IMAGE}

RUN apt update && apt install -y swig ffmpeg
WORKDIR /tmp
RUN git clone https://github.com/pybox2d/pybox2d
WORKDIR /tmp/pybox2d
RUN python3 setup.py build
RUN python3 setup.py install
RUN pip3 install scikit-video keras==2.4.1
RUN pip3 install gym==0.20.0 pyglet


RUN mkdir /tmp/videos
COPY agent_lunar_lander.py .

# WORKDIR /tmp/videos

ENV NVIDIA_VISIBLE_DEVICES 0
ENV CUDA_VISIBLE_DEVICES 0

CMD ["python3", "agent_lunar_lander.py"]

